{% set version = "0.2.1" %}

package:
  name: spiffe-packages
  version: {{ version }}


source:
  - url: https://pypi.org/packages/source/s/spiffe/spiffe-{{ version }}.tar.gz
    sha256: 6db25459655234e9fd4226a106b6beab1c97740362dd64df1b1aeff4bddbf248
    folder: spiffe
  - url: https://pypi.org/packages/source/s/spiffe-tls/spiffe_tls-{{ version }}.tar.gz
    sha256: 5898b91f7e4f8db9f8cbdd00f625a113e2ce5fc7379cf0104c6d19b73d53ddef
    folder: spiffe-tls

build:
  number: 0
  noarch: python

outputs:
  - name: spiffe
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd spiffe
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - python >=3.9
        - pip
        - poetry-core >=1.9.0
      run:
        - python >=3.9
        - grpcio >=1.62
        - cryptography >=42
        - pyjwt >=2
        - pyasn1
        - pyasn1-modules
        - protobuf
        - pem >=23
    test:
      imports:
        - spiffe

  - name: spiffe-tls
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd spiffe-tls
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - python >=3.9
        - pip
        - poetry-core >=1.9.0
      run:
        - python >=3.9
        - pyopenssl >=24
        - spiffe
      run_constrained:
        - spiffe ={{ version }}
    test:
      imports:
        - spiffetls

about:
  home: https://github.com/HewlettPackard/py-spiffe
  license: Apache-2.0
  license_file: spiffe/LICENSE
  summary: Python library for SPIFFE support
  dev_url: https://github.com/HewlettPackard/py-spiffe

extra:
  recipe-maintainers:
    - martinRenou
