{% set version = "0.1.2" %}

package:
  name: spiffe-packages
  version: {{ version }}


source:
  - url: https://pypi.io/packages/source/s/spiffe/spiffe-{{ version }}.tar.gz
    sha256: d33e0e35add6f321297aa3ae3e6a3b4dbbfcab97d2d66bb7fa1f649efb427415
    folder: spiffe
  - url: https://pypi.io/packages/source/s/spiffe-tls/spiffe_tls-{{ version }}.tar.gz
    sha256: 1b0b1968fc89876c998d10c4c4c591efd77eab32ab0e4db4df0e56c5663ad9d6
    folder: spiffe-tls

build:
  number: 0
  noarch: python

outputs:
  - name: spiffe
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd spiffe
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - python >=3.9
        - pip
        - poetry-core >=1.9.0
      run:
        - python >=3.9
        - grpcio >=1.62
        - cryptography >=42
        - pyjwt >=2
        - pyasn1
        - pyasn1-modules
        - protobuf
        - pem >=23
    test:
      imports:
        - spiffe

  - name: spiffe-tls
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd spiffe-tls
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - python >=3.9
        - pip
        - poetry-core >=1.9.0
      run:
        - python >=3.9
        - pyopenssl >=24
        - spiffe
      run_constrained:
        - spiffe ={{ version }}
    test:
      imports:
        - spiffetls

about:
  home: https://github.com/HewlettPackard/py-spiffe
  license: Apache-2.0
  license_file: spiffe/LICENSE
  summary: Python library for SPIFFE support
  dev_url: https://github.com/HewlettPackard/py-spiffe

extra:
  recipe-maintainers:
    - martinRenou
