{% set spiffe_version = "0.2.5" %}
{% set spiffe_tls_version = "0.3.0" %}

package:
  name: spiffe-packages
  version: {{ spiffe_version }}


source:
  - url: https://pypi.org/packages/source/s/spiffe/spiffe-{{ spiffe_version }}.tar.gz
    sha256: 13dca41df7fa10855b33b7d3c07650248fbc638a72811f020b63ca908673911e
    folder: spiffe
  - url: https://pypi.org/packages/source/s/spiffe-tls/spiffe_tls-{{ spiffe_tls_version }}.tar.gz
    sha256: ae22d6b65066f5f3652e963e57957639667c3b3e26386c63285cd1672206c3b7
    folder: spiffe-tls

build:
  number: 0
  noarch: python

outputs:
  - name: spiffe
    version: {{ spiffe_version }}
    build:
      noarch: python
      script: |
        cd spiffe
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - poetry-core >=1.9.0
      run:
        - python >={{ python_min }}
        - grpcio >=1.62
        - cryptography >=42
        - pyjwt >=2
        - pyasn1
        - pyasn1-modules
        - protobuf
        - pem >=23
    test:
      imports:
        - spiffe

  - name: spiffe-tls
    version: {{ spiffe_tls_version }}
    build:
      noarch: python
      script: |
        cd spiffe-tls
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - poetry-core >=1.9.0
      run:
        - python >={{ python_min }}
        - pyopenssl >=24
        - spiffe
      run_constrained:
        - spiffe ={{ spiffe_version }}
    test:
      imports:
        - spiffetls

about:
  home: https://github.com/HewlettPackard/py-spiffe
  license: Apache-2.0
  license_file: spiffe/LICENSE
  summary: Python library for SPIFFE support
  dev_url: https://github.com/HewlettPackard/py-spiffe

extra:
  recipe-maintainers:
    - JohanMabille
    - martinRenou
